### DISCUSSION TITLE
Track naming

### DISCUSSION THREAD

**Discussion by SenorSmartyPants** [Neurrone/beets-audible#29] [Show and tell]
I made a few rounds of changes to how I name individual files of my audiobooks using beets. Here's a copy of the config given in the beets-audible readme.

```yaml
# Place books in their own folders to be compatible with Booksonic and Audiobookshelf servers
paths:
  # For books that belong to a series
  "albumtype:audiobook series_name::.+ series_position::.+": $albumartist/%ifdef{series_name}/%ifdef{series_position} - $album%aunique{}/$track - $title
  "albumtype:audiobook series_name::.+": $albumartist/%ifdef{series_name}/$album%aunique{}/$track - $title
  # Stand-alone books
  "albumtype:audiobook": $albumartist/$album%aunique{}/$track - $title
```

`$track - $title` is the area of concern.

First thing I wanted to change was for books with just one file, I didn't want a track number in the filename. For these examples you need to add the `inline` plugin to your config. I did this so I could do more complicated logic and save it to a variable. The logic after `track_and_title` checks if there is more than one track/file for this book, if there is output the track (padded to 2 digits) and title, otherwise, just output the title. This works well for single file M4Bs.

```yaml
item_fields:
  track_and_title: u'%02i - %s' % (track, title) if tracktotal > 1 else title

paths:
  # For books that belong to a series
  "albumtype:audiobook series_name::.+ series_position::.+": $albumartist/%ifdef{series_name}/%ifdef{series_position} - $album%aunique{}/$track_and_title
  "albumtype:audiobook series_name::.+": $albumartist/%ifdef{series_name}/$album%aunique{}/$track_and_title
  # Stand-alone books
  "albumtype:audiobook": $albumartist/$album%aunique{}/$track_and_title
```

After importing more of my mp3 library I ran into tracks that I had named as `Chapter XX - Title.mp3`. Beets wanted to rename them as `XX - Chapter XX - Title.mp3` . I didn't want the extra track numbers in those cases where the track number matched the chapter number. So I changed track_and_title to use a regular expression to check the title if it contained a couple variations.
`Chapter XX - `
`Chapter XX:`
`Chapter XX `
`XX - `
`XX:`
`XX `
If those are found in the title, just use the title to name the file. But if chapter numbers don't match, it will rename to something like `06 - Chapter 3.mp3`

```yaml
item_fields:
  track_and_title: |
    import re
    regex = r'(Chapter )?0*' + str(track) + r'( -|:)? '
    return u'%02i - %s' % (track, title) if tracktotal > 1 and re.match(regex, title) is None else title
```
