### DISCUSSION TITLE
Album disambiguation/duplicates

### DISCUSSION THREAD

**Discussion by SenorSmartyPants** [Neurrone/beets-audible#30] [Show and tell]
I have both the US and UK versions of Harry Potter. When importing those beets decides that since the author and book title (albumartist and album) are the same they must be duplicates. But you can customize this in the config.

[aunique](https://beets.readthedocs.io/en/stable/reference/pathformat.html#aunique) is the section needed. But one problem I ran into was that `series` seemed to be an item level field. So I included the album_fields section to just convert it to an album level one. Only album level fields can be used in aunique.

```yaml
aunique:
  keys: albumartist series album

album_fields:
  series: items[0].get('series_name','')
```

I also messed around a little with disambiguators. Here I added narrator as an album field and used that as my first disambiguators. It was using catalognum before I made a change. I also changed what kind of bracket it uses, since audiobookshelf seems to like narrators in curly braces.

```yaml
aunique:
  keys: albumartist series album
  disambiguators: narrator year label catalognum albumdisambig releasegroupdisambig albumtype
  #default disambig : albumtype year label catalognum albumdisambig releasegroupdisambig
  bracket: '{}'

album_fields:
  narrator: items[0].composer
  series: items[0].get('series_name','')
```
