### DISCUSSION TITLE
series_name strips The from the title, anyway to get this back

### DISCUSSION THREAD

**Discussion by TheKronzo** [Neurrone/beets-audible#70] [Q&A] [answered]
I'm rather new to beets, but have been looking at all the documentation I can find, but it seems like this plugin strips the from the series name, is this correct ?

Is there anyway to get it back,?
I'm trying to get my naming scheme to match calibre

**Comment by SenorSmartyPants** [comment, marked as answer]
I quick looked over the code, I don't think series name is altered. Have you looked at the audible.com page to check if they have the "The" in the series name there?

You can use beets edit or modify to tweak the series name after you run this plugin.

**Comment by TheKronzo** [comment]
You are correct.
I did check audible.com previously, and it did list it in big  **The Vampires of Shadow Hills.** The other file I checked with, was of course from the same series (stupid mistake :))
now as i checked again, in the buttom right corner it just said vampires of shadow hills, so you are correct that was the problem.

I saw your change to track numbers and implemented it, thank you for that.

would you help me with this one.
`  "albumtype:audiobook series_name::.+ series_position::.+": $albumartist/**%ifdef{series_name}**/Vol $padded_series_position - $album%aunique{} - %if{$hasyear,($year)}/$track_and_title`

I need to add the, the plugin to the series name, but I can't get it correct (can't escape %the correct at %ifdef(series_name))
```
# Configure the "the" plugin to move articles in strings
the:
  a: yes           # Process "A"/"An"
  the: yes         # Process "The"
  patterns: []     # Use default patterns (or add custom ones here)
  strip: no        # Do not remove the article, just move it
  format: '{0}, {1}'  # Format output: main part, then the article    
```
