### ISSUE TITLE
Beets-audible searches using musicbrainz instead of audnexus despite correct installation of all plugins 

### ISSUE THREAD

**Issue by trustosas** [Neurrone/beets-audible#48]
Here's the output of trying importing an audiobook:
```
beets version 1.6.0
Python version 3.9.16
plugins: audible, copyartifacts, edit, fromfilename, scrub
user configuration: /content/config.yaml
data directory: /content
plugin paths: 
Sending event: pluginload
library database: /content/library.db
library directory: /content/drive/MyDrive/audiobooks
Sending event: library_opened
Sending event: import_begin
state file could not be read: [Errno 2] No such file or directory: '/content/state.pickle'
ignoring b'.ipynb_checkpoints' due to ignore rule b'.*'
Sending event: import_task_created
Sending event: import_task_start
Looking up: /content/drive/MyDrive/temp
Tagging B07FTVRVG6 - Falling Awake: How to Practice Mindfulness in Everyday Life
No album ID found.
Search terms: B07FTVRVG6 - Falling Awake: How to Practice Mindfulness in Everyday Life
Album might be VA: False
Searching for MusicBrainz releases with: {'release': 'falling awake: how to practice mindfulness in everyday life', 'artist': 'b07ftvrvg6', 'tracks': '1'}
Requesting MusicBrainz release b5e038a2-398f-43ef-8527-d274a67bbde7
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Bill Nelson - The Practice of Everyday Life (b5e038a2-398f-43ef-8527-d274a67bbde7)
Computing track assignment...
...done.
Success. Distance: 0.99
Requesting MusicBrainz release 33381eb9-aa4f-4491-9991-7dc34cb41597
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Goodnight Sunrise - Falling Awake (33381eb9-aa4f-4491-9991-7dc34cb41597)
Computing track assignment...
...done.
Success. Distance: 0.89
Requesting MusicBrainz release 103cb400-cb6d-4c05-a483-bd52ca20c644
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Michael Kelsey - Falling Awake (103cb400-cb6d-4c05-a483-bd52ca20c644)
Computing track assignment...
...done.
Success. Distance: 0.89
Requesting MusicBrainz release 38d71ac7-1756-4b49-b28f-2de7ada45883
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Goodnight Sunrise - Falling Awake (38d71ac7-1756-4b49-b28f-2de7ada45883)
Computing track assignment...
...done.
Success. Distance: 0.89
Requesting MusicBrainz release 1c330c26-fc10-4fab-a8b1-7fd2b53dc5f8
Sending event: mb_track_extract
Sending event: mb_track_extract
Sending event: mb_album_extract
Sending event: albuminfo_received
Candidate: Kaiser Chiefs - Falling Awake (1c330c26-fc10-4fab-a8b1-7fd2b53dc5f8)
Computing track assignment...
...done.
Success. Distance: 0.78
audible: Searching Audible for Falling Awake: How to Practice Mindfulness in Everyday Life B07FTVRVG6
Evaluating 5 candidates.

/content/drive/MyDrive/temp (1 items)
Sending event: import_task_before_choice
Sending event: before_choose_candidate
Correcting tags from:
    B07FTVRVG6 - Falling Awake: How to Practice Mindfulness in Everyday Life
To:
    Kaiser Chiefs - Falling Awake
URL:
    https://musicbrainz.org/release/1c330c26-fc10-4fab-a8b1-7fd2b53dc5f8
(Similarity: 21.6%) (artist, album, missing tracks, tracks) (CD-R, 2015, XE, Caroline Records, EDUCATE09)
 * Falling Awake (#0) (310:18) ->
   Falling Awake (#1) (3:55) (length)
Missing tracks (1/2 - 50.0%):
 ! Falling Awake (instrumental) (# 2) (3:56)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? ^C
```

Instead of searching using audible, it tries to use musicbrainz.
Here's my config:

```

plugins: audible copyartifacts edit fromfilename scrub
directory: /content/drive/MyDrive/audiobooks

import:
    move: no

paths:
    albumtype:audiobook series_name::.+ series_position::.+: $albumartist/%ifdef{series_name}/%ifdef{series_position} - $album%aunique{}/$track - $title
    albumtype:audiobook series_name::.+: $albumartist/%ifdef{series_name}/$album%aunique{}/$track - $title
    albumtype:audiobook: $albumartist/$album%aunique{}/$track - $title
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

musicbrainz:
    enabled: no
audible:
    match_chapters: yes
    source_weight: 0.0
    fetch_art: no
    include_narrator_in_artists: yes
    write_description_file: yes
    write_reader_file: yes
    goodreads_apikey: REDACTED
copyartifacts:
    extensions: .yml
    print_ignored: no

match:
    strong_rec_thresh: 1
scrub:
    auto: yes
edit:
    albumfields: albumartist
    itemfields: track title artist
    ignore_fields: id path

```
