### ISSUE TITLE
Error with plugins when starting up

### ISSUE THREAD

**Issue by Julian-mostert** [Neurrone/beets-audible#56]
```
beets  | cp: not replacing '/config/beets.sh'
beets  | cp: not replacing '/config/config.yaml'
beets  | [custom-init] No custom files found, skipping...
beets  | ** error loading plugin copyartifacts:
beets  | Traceback (most recent call last):
beets  |   File "/lsiopy/lib/python3.11/site-packages/beets/plugins.py", line 268, in load_plugins
beets  |     namespace = __import__(modname, None, None)
beets  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
beets  | ModuleNotFoundError: No module named 'beetsplug.copyartifacts'
beets  | 
beets  | ** error loading plugin audible:
beets  | Traceback (most recent call last):
beets  |   File "/lsiopy/lib/python3.11/site-packages/beets/plugins.py", line 268, in load_plugins
beets  |     namespace = __import__(modname, None, None)
beets  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
beets  |   File "/plugins/audible/audible.py", line 13, in <module>
beets  |     from natsort import os_sorted
beets  | ModuleNotFoundError: No module named 'natsort'
beets  | 
beets  |  * Serving Flask app 'beetsplug.web'
beets  |  * Debug mode: off
```

**Comment by Neurrone** [comment]
Can you provide any additional information such as how you're trying to run it? Otherwise, I won't be able to help with just this error message alone.

**Comment by Julian-mostert** [comment]
thanks 
im running it from a docker container 

```yml
version: "3"
services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      # Update as needed
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - ./config:/config
      - ./plugins:/plugins
      - ./scripts:/config/custom-cont-init.d
      - G:\Audiobooks:/audiobooks
      - G:\temp\untagged:/untagged
    restart: unless-stopped

```
