### ISSUE TITLE
Install with Portainer on Docker

### ISSUE THREAD

**Issue by kcossabo** [Neurrone/beets-audible#57]
Installing on Ubuntu with Portainer as a 'stack' (Compose)

Not finding audiobook tag, and not listing audiable as a source.

**output of beet**

```
root@04f73e0003e1:/# beet --version
beets version 1.6.0
Python version 3.10.12
plugins: chroma, convert, embedart, fetchart, lastgenre, replaygain, scrub, web
root@04f73e0003e1:/# 
```

**Directory**

```
.
├── config
│   ├── beets.sh
│   ├── config.yaml
│   └── musiclibrary.blb
├── docker-compose.yml
└── scripts
    └── install-deps.sh

```

**compose** 

```
version: "3"
services:
  beets:
    image: lscr.io/linuxserver/beets:1.6.0-ls180
    container_name: beets
    environment:
      # Update as needed
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /mnt/data/docker/config/beets/config:/config
      - /mnt/data/docker/config/beets/scripts:/custom-cont-init.d
      - /mnt/data/NAS2/audiobooks/done:/audiobooks
      - /mnt/data/NAS2/audiobook/untagged:/input
 ```
      
      **log**
      
```   
Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    100
───────────────────────────────────────
[custom-init] Files found, executing
[custom-init] install-deps.sh: executing...
Installing dependencies...
Requirement already satisfied: beets-audible in /usr/lib/python3.10/site-packages (0.1.0)
Requirement already satisfied: beets-copyartifacts3 in /usr/lib/python3.10/site-packages (0.1.5)
Requirement already satisfied: markdownify==0.11.6 in /usr/lib/python3.10/site-packages (from beets-audible) (0.11.6)
Requirement already satisfied: natsort==8.2.0 in /usr/lib/python3.10/site-packages (from beets-audible) (8.2.0)
Requirement already satisfied: beautifulsoup4<5,>=4.9 in /usr/lib/python3.10/site-packages (from markdownify==0.11.6->beets-audible) (4.12.2)
Requirement already satisfied: six<2,>=1.15 in /usr/lib/python3.10/site-packages (from markdownify==0.11.6->beets-audible) (1.16.0)
Requirement already satisfied: beets>=1.3.11 in /usr/lib/python3.10/site-packages (from beets-copyartifacts3) (1.6.0)
Requirement already satisfied: unidecode in /usr/lib/python3.10/site-packages (from beets>=1.3.11->beets-copyartifacts3) (1.3.6)
Requirement already satisfied: musicbrainzngs>=0.4 in /usr/lib/python3.10/site-packages (from beets>=1.3.11->beets-copyartifacts3) (0.7.1)
Requirement already satisfied: pyyaml in /usr/lib/python3.10/site-packages (from beets>=1.3.11->beets-copyartifacts3) (6.0.1)
Requirement already satisfied: mediafile>=0.2.0 in /usr/lib/python3.10/site-packages (from beets>=1.3.11->beets-copyartifacts3) (0.12.0)
Requirement already satisfied: confuse>=1.0.0 in /usr/lib/python3.10/site-packages (from beets>=1.3.11->beets-copyartifacts3) (2.0.1)
Requirement already satisfied: munkres>=1.0.0 in /usr/lib/python3.10/site-packages (from beets>=1.3.11->beets-copyartifacts3) (1.1.4)
Requirement already satisfied: jellyfish in /usr/lib/python3.10/site-packages (from beets>=1.3.11->beets-copyartifacts3) (1.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3.10/site-packages (from beautifulsoup4<5,>=4.9->markdownify==0.11.6->beets-audible) (2.4.1)
Requirement already satisfied: mutagen>=1.46 in /usr/lib/python3.10/site-packages (from mediafile>=0.2.0->beets>=1.3.11->beets-copyartifacts3) (1.46.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[custom-init] install-deps.sh: exited 0
 * Serving Flask app 'beetsplug.web'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8337
 * Running on http://172.22.0.2:8337
Press CTRL+C to quit
[ls.io-init] done.
```

**Comment by Neurrone** [comment]
Can you exec into the container and check that the Beets config file is mapped into the container correctly?

**Comment by kcossabo** [comment]
I did some reading on beet and I do not think I have the config ??

My directory is not 

> directory: /music

```
root@a96de43c70e6:/# beet config

plugins: fetchart embedart convert scrub replaygain lastgenre chroma web
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no
convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1
    dest:
    pretend: no
    link: no
    hardlink: no
    format: mp3
    id3v23: inherit
    formats:
        aac:
            command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
            extension: m4a
        alac:
            command: ffmpeg -i $source -y -vn -acodec alac $dest
            extension: m4a
        flac: ffmpeg -i $source -y -vn -acodec flac $dest
        mp3: ffmpeg -i $source -y -vn -aq 2 $dest
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 96k $dest
        ogg: ffmpeg -i $source -y -vn -acodec libvorbis -aq 3 $dest
        wma: ffmpeg -i $source -y -vn -acodec wmav2 -vn $dest
    tmpdir:
    quiet: no
    embed: yes

    paths: {}
    no_convert: ''
    never_convert_lossy_files: no
    copy_album_art: no
    album_art_maxwidth: 0
    delete_originals: no

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log
lastgenre:
    auto: yes
    source: album
    whitelist: yes
    min_weight: 10
    count: 1
    fallback:
    canonical: no
    force: yes
    separator: ', '
    prefer_specific: no
    title_case: yes
embedart:
    auto: yes
    maxwidth: 0
    compare_threshold: 0
    ifempty: no
    remove_art_file: no
    quality: 0
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
replaygain:
    auto: no
    overwrite: no
    backend: command
    threads: 8
    parallel_on_import: no
    per_disc: no
    peak: 'true'
    targetlevel: 89
    r128: [Opus]
    r128_targetlevel: 84
    command: ''
    noclip: yes
scrub:
    auto: yes

replace:
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    \.$: _
    \s+$: ''
web:
    host: 0.0.0.0
    port: 8337
    cors: ''
    cors_supports_credentials: no
    reverse_proxy: no
    include_paths: no
    readonly: yes
chroma:
    auto: yes
```
