### ISSUE TITLE
Folders are being created as root

### ISSUE THREAD

**Issue by alexander-paterson** [Neurrone/beets-audible#64]
When I run `beet import /input` the folders that get created are owned by root instead of my user.

This is my docker compose file

```
version: "3"
services:
  beets:
    image: lscr.io/linuxserver/beets:1.6.0-ls180
    container_name: beets
    environment:
      # Update as needed
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
    ports:
      - 8337:8337
    volumes:
      - /srv/dev-disk-by-uuid-f94e80d8-a1e4-4ee9-8ca1-dbef7eb0d715/_docker_configs/beets/config:/config
      - /srv/dev-disk-by-uuid-f94e80d8-a1e4-4ee9-8ca1-dbef7eb0d715/_docker_configs/beets/scripts:/custom-cont-init.d
      - /srv/dev-disk-by-uuid-ac34a28b-4afa-4cbd-aa8f-1d273b35380b/more_media/audiobooks:/audiobooks
      - /srv/dev-disk-by-uuid-a4322c9b-c2f7-4120-8b71-1444f5d201f2/_downloads/books:/import
    restart: unless-stopped
networks: {}
```
Looking in the terminal, it appears that beets is running as the correct user.

![firefox_Afd1Z6rXVJ](https://github.com/user-attachments/assets/9c38599a-4b05-4820-8e87-e885f14215aa)
